let ApiUrl = 'https://xwz.dd371.com/api/';

const api = {
    ApiWechat: ApiUrl + 'login/login',
    ApiIndex: ApiUrl + 'index/index',
    ApiNewDetail: ApiUrl + 'user/news_detail',
    ApiTeacher: ApiUrl + 'index/teacher',
    ApiNews: ApiUrl + 'index/news',
    ApiType: ApiUrl + 'index/type',
    ApiDetail: ApiUrl + 'user/detail',
    ApiDancerType: ApiUrl + 'user/dancer_type',
    ApiUserIndex: ApiUrl + 'user/index',
    ApiDancerSave: ApiUrl + 'user/dancer_save',
    ApiOrganIndex: ApiUrl + 'organ/index',
    ApiOrganDetail: ApiUrl + 'user/organ_detail',
    ApiDetailJob: ApiUrl + 'organ/detail_job',
    ApiCooper: ApiUrl + 'user/cooper',
    ApiDancer: ApiUrl + 'user/dancer',
    ApiMyRelease: ApiUrl + 'user/my_release?status=1',
    ApiTypeLister: ApiUrl + 'index/type_lister',
    ApiSaveJob: ApiUrl + 'user/save_job',
    ApiIndexSearch: ApiUrl + 'index/search',
    ApiIndexSearchLister: ApiUrl + 'index/type_lister',
    ApiOrganSave: ApiUrl + 'user/organ_save',
    ApiOrgan: ApiUrl + 'user/organ',
    ApiOrganType: ApiUrl + 'organ/organ_type',
    ApiAddImg: ApiUrl + 'index/add_img',
    ApiTeacherDetail: ApiUrl + 'user/teacher_detail',
    ApiDelete: ApiUrl + 'user/delete',
    ApiAddImg: ApiUrl + 'index/add_img',
    ApiSearch: ApiUrl + 'organ/search',
    ApiLister: ApiUrl + 'organ/lister',
}
module.exports = api;